name: syncimagetoaliyunexample
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: gitpull
        uses: actions/checkout@v3
      - name: setupdockerbuildx
        uses: docker/setup-buildx-action@v2.9.1
      - name: logintodockerhub
        uses: docker/login-action@v2.2.0
        with:
          registry: crpi-i709826kmwno8b49.cn-qingdao.personal.cr.aliyuncs.com
          username: jyns980
          password: ph65473f
          logout: false
      - name: use1skopeotoolssyncimagetodockerhub
        run: |
          skopeo copy docker://rancher/shell:v0.1.18 docker://infiniflow/ragflow/rancher-shell:v0.1.18
